# context.modules = [
# { name = libpipewire-module-loopback
#   args = {
#     node.description = "AIR 192 6 Analog Mono"
#
#     capture.props = {
#       audio.position = [ FL ]
#       node.target = "alsa_input.usb-M-Audio_AIR_192_6-00.analog-stereo"
#       node.passive = true
#       stream.dont-remix = true
#     }
#
#     playback.props = {
#       node.name = "M-Audio_AIR_192_6-00.analog-mono"
#       media.class = "Audio/Source"
#       audio.position = [ MONO ]
#     }
#   }
# }
# ]
#
